# Generated by Django 2.1.5 on 2019-02-28 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190228_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Статус заказа', 'verbose_name_plural': 'Статусы заказа'},
        ),
        migrations.RenameField(
            model_name='orderstatus',
            old_name='status',
            new_name='status_name',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='description',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='status_date',
        ),
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.OrderStatus'),
        ),
    ]
