# Generated by Django 2.1.5 on 2019-02-28 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190228_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='client_address',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='client_firstname',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='client_lastname',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='client_phone',
        ),
    ]
