# Generated by Django 2.1.5 on 2019-03-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товары в заказе'},
        ),
    ]
