# Generated by Django 2.1.5 on 2019-03-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_productincart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='session_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
