# Generated by Django 2.1.5 on 2019-03-11 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_productincart_session_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='order_total_price',
        ),
    ]
