# Generated by Django 2.1.5 on 2019-03-12 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0010_auto_20190311_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('cart_total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client_email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('client_firstname', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('client_lastname', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('client_phone', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('client_address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('delivery_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Delivery')),
                ('items', models.ManyToManyField(blank=True, to='order.ProductInCart')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Payment')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.OrderStatus')),
            ],
        ),
    ]
