# Generated by Django 2.1.5 on 2019-03-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='size',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
