# Generated by Django 2.1.5 on 2019-03-13 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_productincart_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='client_address',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='client_firstname',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='client_lastname',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='client_phone',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='delivery_method',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
    ]
