# Generated by Django 2.1.5 on 2019-03-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20190313_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
