# Generated by Django 2.1.5 on 2019-02-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_gender',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='quantity',
            field=models.SmallIntegerField(),
        ),
    ]
