# Generated by Django 2.1.5 on 2019-02-05 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190205_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='collection_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='sale_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='store_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Category'),
        ),
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='collection',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Collection'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Collection'),
        ),
        migrations.AlterField(
            model_name='product',
            name='insert_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='insertion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_gender',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.RemoveField(
            model_name='sale',
            name='collection',
        ),
        migrations.AddField(
            model_name='sale',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Collection'),
        ),
        migrations.AlterField(
            model_name='store',
            name='product_name',
            field=models.ManyToManyField(null=True, to='store.Product'),
        ),
        migrations.AlterField(
            model_name='store',
            name='quantity',
            field=models.SmallIntegerField(default=0),
        ),
    ]
