# Generated by Django 2.1.5 on 2019-02-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190205_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='product_name',
            field=models.ManyToManyField(to='store.Product'),
        ),
    ]
