# Generated by Django 2.1.5 on 2019-02-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190228_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_for',
            field=models.PositiveSmallIntegerField(choices=[(0, 'унисекс'), (1, 'женщине'), (2, 'мужчине')], default=1),
        ),
    ]
