# Generated by Django 2.1.5 on 2019-02-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20190228_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='size',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
