# Generated by Django 2.1.5 on 2019-02-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='category_img'),
        ),
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(null=True, upload_to='collect_img'),
        ),
    ]
