# Generated by Django 2.1.5 on 2019-03-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20190228_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_main_img',
            field=models.BooleanField(default=False),
        ),
    ]
