# Generated by Django 2.1.5 on 2019-03-03 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productimage_is_main_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_percent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Sale'),
        ),
    ]
