# Generated by Django 2.1.5 on 2019-03-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_sale_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
