# Generated by Django 2.1.5 on 2019-03-08 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_user_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user_wishlist',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
