# Generated by Django 2.1.5 on 2019-03-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20190311_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, to='store.Size'),
        ),
    ]
