# Generated by Django 2.1.5 on 2019-03-12 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20190312_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['size'], 'verbose_name': 'Доступный размер', 'verbose_name_plural': 'Доступные размеры'},
        ),
    ]
