# Generated by Django 2.1.5 on 2019-03-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_user_wishlist'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='wishlist',
            field=models.ManyToManyField(blank=True, null=True, to='store.Product'),
        ),
    ]
