# Generated by Django 2.1.5 on 2019-03-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_myuser_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='wishlist',
            field=models.ManyToManyField(blank=True, to='store.Product'),
        ),
    ]
